obj:main.o nsize.o avr.o mark.o age.o
	mv *.o ../obj
main.o:main.c
	gcc -c -g -Wall main.c -o main.o
nsize.o:nsize.c
	gcc -c nsize.c -o nsize.o
avr.o:avr.c
	gcc -c avr.c -o avr.o
mark.o:mark.c
	gcc -c mark.c -o mark.o
age.o:age.c
	gcc -c age.c -o age.o
